version: "2"
linters:
  default: standard
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - contextcheck
    - copyloopvar
    - decorder
    - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exptostd
    - funcorder
    - gocheckcompilerdirectives
    - goconst
    - godot
    - godox
    - gosec
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - iotamixing
    - loggercheck
    - makezero
    - mirror
    - misspell
    - modernize
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - reassign
    - recvcheck
    - staticcheck
    - tagalign
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errname
      - path: _test\.go
        linters:
          - gosec
        text: "G(101|304)"
