// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pkienginereceiver

import (
	"context"
	"sync"
	"time"

	"github.com/go-ldap/ldap/v3"
	"github.com/hashicorp/vault/api"
	mock "github.com/stretchr/testify/mock"
)

// newMockauthMethod creates a new instance of mockauthMethod. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockauthMethod(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockauthMethod {
	mock := &mockauthMethod{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockauthMethod is an autogenerated mock type for the authMethod type
type mockauthMethod struct {
	mock.Mock
}

type mockauthMethod_Expecter struct {
	mock *mock.Mock
}

func (_m *mockauthMethod) EXPECT() *mockauthMethod_Expecter {
	return &mockauthMethod_Expecter{mock: &_m.Mock}
}

// authenticate provides a mock function for the type mockauthMethod
func (_mock *mockauthMethod) authenticate(ctx context.Context, client *api.Client) (*api.Secret, error) {
	ret := _mock.Called(ctx, client)

	if len(ret) == 0 {
		panic("no return value specified for authenticate")
	}

	var r0 *api.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *api.Client) (*api.Secret, error)); ok {
		return returnFunc(ctx, client)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *api.Client) *api.Secret); ok {
		r0 = returnFunc(ctx, client)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *api.Client) error); ok {
		r1 = returnFunc(ctx, client)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockauthMethod_authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'authenticate'
type mockauthMethod_authenticate_Call struct {
	*mock.Call
}

// authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - client *api.Client
func (_e *mockauthMethod_Expecter) authenticate(ctx interface{}, client interface{}) *mockauthMethod_authenticate_Call {
	return &mockauthMethod_authenticate_Call{Call: _e.mock.On("authenticate", ctx, client)}
}

func (_c *mockauthMethod_authenticate_Call) Run(run func(ctx context.Context, client *api.Client)) *mockauthMethod_authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *api.Client
		if args[1] != nil {
			arg1 = args[1].(*api.Client)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockauthMethod_authenticate_Call) Return(secret *api.Secret, err error) *mockauthMethod_authenticate_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *mockauthMethod_authenticate_Call) RunAndReturn(run func(ctx context.Context, client *api.Client) (*api.Secret, error)) *mockauthMethod_authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// newMockcrlCacheStore creates a new instance of mockcrlCacheStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockcrlCacheStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockcrlCacheStore {
	mock := &mockcrlCacheStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockcrlCacheStore is an autogenerated mock type for the crlCacheStore type
type mockcrlCacheStore struct {
	mock.Mock
}

type mockcrlCacheStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockcrlCacheStore) EXPECT() *mockcrlCacheStore_Expecter {
	return &mockcrlCacheStore_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type mockcrlCacheStore
func (_mock *mockcrlCacheStore) Add(key string, value crlCacheEntry) {
	_mock.Called(key, value)
	return
}

// mockcrlCacheStore_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type mockcrlCacheStore_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - key string
//   - value crlCacheEntry
func (_e *mockcrlCacheStore_Expecter) Add(key interface{}, value interface{}) *mockcrlCacheStore_Add_Call {
	return &mockcrlCacheStore_Add_Call{Call: _e.mock.On("Add", key, value)}
}

func (_c *mockcrlCacheStore_Add_Call) Run(run func(key string, value crlCacheEntry)) *mockcrlCacheStore_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 crlCacheEntry
		if args[1] != nil {
			arg1 = args[1].(crlCacheEntry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockcrlCacheStore_Add_Call) Return() *mockcrlCacheStore_Add_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockcrlCacheStore_Add_Call) RunAndReturn(run func(key string, value crlCacheEntry)) *mockcrlCacheStore_Add_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type mockcrlCacheStore
func (_mock *mockcrlCacheStore) Get(key string) (crlCacheEntry, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 crlCacheEntry
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (crlCacheEntry, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) crlCacheEntry); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(crlCacheEntry)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// mockcrlCacheStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockcrlCacheStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *mockcrlCacheStore_Expecter) Get(key interface{}) *mockcrlCacheStore_Get_Call {
	return &mockcrlCacheStore_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *mockcrlCacheStore_Get_Call) Run(run func(key string)) *mockcrlCacheStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockcrlCacheStore_Get_Call) Return(crlCacheEntryMoqParam crlCacheEntry, b bool) *mockcrlCacheStore_Get_Call {
	_c.Call.Return(crlCacheEntryMoqParam, b)
	return _c
}

func (_c *mockcrlCacheStore_Get_Call) RunAndReturn(run func(key string) (crlCacheEntry, bool)) *mockcrlCacheStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type mockcrlCacheStore
func (_mock *mockcrlCacheStore) Remove(key string) {
	_mock.Called(key)
	return
}

// mockcrlCacheStore_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type mockcrlCacheStore_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - key string
func (_e *mockcrlCacheStore_Expecter) Remove(key interface{}) *mockcrlCacheStore_Remove_Call {
	return &mockcrlCacheStore_Remove_Call{Call: _e.mock.On("Remove", key)}
}

func (_c *mockcrlCacheStore_Remove_Call) Run(run func(key string)) *mockcrlCacheStore_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockcrlCacheStore_Remove_Call) Return() *mockcrlCacheStore_Remove_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockcrlCacheStore_Remove_Call) RunAndReturn(run func(key string)) *mockcrlCacheStore_Remove_Call {
	_c.Run(run)
	return _c
}

// newMockcrlFetcher creates a new instance of mockcrlFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockcrlFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockcrlFetcher {
	mock := &mockcrlFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockcrlFetcher is an autogenerated mock type for the crlFetcher type
type mockcrlFetcher struct {
	mock.Mock
}

type mockcrlFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockcrlFetcher) EXPECT() *mockcrlFetcher_Expecter {
	return &mockcrlFetcher_Expecter{mock: &_m.Mock}
}

// fetch provides a mock function for the type mockcrlFetcher
func (_mock *mockcrlFetcher) fetch(ctx context.Context, uri string, timeout time.Duration, previousETag string, previousLastModified time.Time) (fetchResult, error) {
	ret := _mock.Called(ctx, uri, timeout, previousETag, previousLastModified)

	if len(ret) == 0 {
		panic("no return value specified for fetch")
	}

	var r0 fetchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration, string, time.Time) (fetchResult, error)); ok {
		return returnFunc(ctx, uri, timeout, previousETag, previousLastModified)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration, string, time.Time) fetchResult); ok {
		r0 = returnFunc(ctx, uri, timeout, previousETag, previousLastModified)
	} else {
		r0 = ret.Get(0).(fetchResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration, string, time.Time) error); ok {
		r1 = returnFunc(ctx, uri, timeout, previousETag, previousLastModified)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockcrlFetcher_fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'fetch'
type mockcrlFetcher_fetch_Call struct {
	*mock.Call
}

// fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - uri string
//   - timeout time.Duration
//   - previousETag string
//   - previousLastModified time.Time
func (_e *mockcrlFetcher_Expecter) fetch(ctx interface{}, uri interface{}, timeout interface{}, previousETag interface{}, previousLastModified interface{}) *mockcrlFetcher_fetch_Call {
	return &mockcrlFetcher_fetch_Call{Call: _e.mock.On("fetch", ctx, uri, timeout, previousETag, previousLastModified)}
}

func (_c *mockcrlFetcher_fetch_Call) Run(run func(ctx context.Context, uri string, timeout time.Duration, previousETag string, previousLastModified time.Time)) *mockcrlFetcher_fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *mockcrlFetcher_fetch_Call) Return(fetchResultMoqParam fetchResult, err error) *mockcrlFetcher_fetch_Call {
	_c.Call.Return(fetchResultMoqParam, err)
	return _c
}

func (_c *mockcrlFetcher_fetch_Call) RunAndReturn(run func(ctx context.Context, uri string, timeout time.Duration, previousETag string, previousLastModified time.Time) (fetchResult, error)) *mockcrlFetcher_fetch_Call {
	_c.Call.Return(run)
	return _c
}

// fetchHTTP provides a mock function for the type mockcrlFetcher
func (_mock *mockcrlFetcher) fetchHTTP(ctx context.Context, uri string, timeout time.Duration, previousETag string, previousLastModified time.Time) (fetchResult, error) {
	ret := _mock.Called(ctx, uri, timeout, previousETag, previousLastModified)

	if len(ret) == 0 {
		panic("no return value specified for fetchHTTP")
	}

	var r0 fetchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration, string, time.Time) (fetchResult, error)); ok {
		return returnFunc(ctx, uri, timeout, previousETag, previousLastModified)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration, string, time.Time) fetchResult); ok {
		r0 = returnFunc(ctx, uri, timeout, previousETag, previousLastModified)
	} else {
		r0 = ret.Get(0).(fetchResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration, string, time.Time) error); ok {
		r1 = returnFunc(ctx, uri, timeout, previousETag, previousLastModified)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockcrlFetcher_fetchHTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'fetchHTTP'
type mockcrlFetcher_fetchHTTP_Call struct {
	*mock.Call
}

// fetchHTTP is a helper method to define mock.On call
//   - ctx context.Context
//   - uri string
//   - timeout time.Duration
//   - previousETag string
//   - previousLastModified time.Time
func (_e *mockcrlFetcher_Expecter) fetchHTTP(ctx interface{}, uri interface{}, timeout interface{}, previousETag interface{}, previousLastModified interface{}) *mockcrlFetcher_fetchHTTP_Call {
	return &mockcrlFetcher_fetchHTTP_Call{Call: _e.mock.On("fetchHTTP", ctx, uri, timeout, previousETag, previousLastModified)}
}

func (_c *mockcrlFetcher_fetchHTTP_Call) Run(run func(ctx context.Context, uri string, timeout time.Duration, previousETag string, previousLastModified time.Time)) *mockcrlFetcher_fetchHTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *mockcrlFetcher_fetchHTTP_Call) Return(fetchResultMoqParam fetchResult, err error) *mockcrlFetcher_fetchHTTP_Call {
	_c.Call.Return(fetchResultMoqParam, err)
	return _c
}

func (_c *mockcrlFetcher_fetchHTTP_Call) RunAndReturn(run func(ctx context.Context, uri string, timeout time.Duration, previousETag string, previousLastModified time.Time) (fetchResult, error)) *mockcrlFetcher_fetchHTTP_Call {
	_c.Call.Return(run)
	return _c
}

// fetchLDAP provides a mock function for the type mockcrlFetcher
func (_mock *mockcrlFetcher) fetchLDAP(ctx context.Context, dialer ldapDialer, uri string, timeout time.Duration) (int64, []byte, error) {
	ret := _mock.Called(ctx, dialer, uri, timeout)

	if len(ret) == 0 {
		panic("no return value specified for fetchLDAP")
	}

	var r0 int64
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ldapDialer, string, time.Duration) (int64, []byte, error)); ok {
		return returnFunc(ctx, dialer, uri, timeout)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ldapDialer, string, time.Duration) int64); ok {
		r0 = returnFunc(ctx, dialer, uri, timeout)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ldapDialer, string, time.Duration) []byte); ok {
		r1 = returnFunc(ctx, dialer, uri, timeout)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, ldapDialer, string, time.Duration) error); ok {
		r2 = returnFunc(ctx, dialer, uri, timeout)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// mockcrlFetcher_fetchLDAP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'fetchLDAP'
type mockcrlFetcher_fetchLDAP_Call struct {
	*mock.Call
}

// fetchLDAP is a helper method to define mock.On call
//   - ctx context.Context
//   - dialer ldapDialer
//   - uri string
//   - timeout time.Duration
func (_e *mockcrlFetcher_Expecter) fetchLDAP(ctx interface{}, dialer interface{}, uri interface{}, timeout interface{}) *mockcrlFetcher_fetchLDAP_Call {
	return &mockcrlFetcher_fetchLDAP_Call{Call: _e.mock.On("fetchLDAP", ctx, dialer, uri, timeout)}
}

func (_c *mockcrlFetcher_fetchLDAP_Call) Run(run func(ctx context.Context, dialer ldapDialer, uri string, timeout time.Duration)) *mockcrlFetcher_fetchLDAP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ldapDialer
		if args[1] != nil {
			arg1 = args[1].(ldapDialer)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockcrlFetcher_fetchLDAP_Call) Return(n int64, bytes []byte, err error) *mockcrlFetcher_fetchLDAP_Call {
	_c.Call.Return(n, bytes, err)
	return _c
}

func (_c *mockcrlFetcher_fetchLDAP_Call) RunAndReturn(run func(ctx context.Context, dialer ldapDialer, uri string, timeout time.Duration) (int64, []byte, error)) *mockcrlFetcher_fetchLDAP_Call {
	_c.Call.Return(run)
	return _c
}

// newMocksecretStore creates a new instance of mocksecretStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocksecretStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocksecretStore {
	mock := &mocksecretStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocksecretStore is an autogenerated mock type for the secretStore type
type mocksecretStore struct {
	mock.Mock
}

type mocksecretStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mocksecretStore) EXPECT() *mocksecretStore_Expecter {
	return &mocksecretStore_Expecter{mock: &_m.Mock}
}

// listCertificates provides a mock function for the type mocksecretStore
func (_mock *mocksecretStore) listCertificates(ctx context.Context, mount string) (*api.Secret, error) {
	ret := _mock.Called(ctx, mount)

	if len(ret) == 0 {
		panic("no return value specified for listCertificates")
	}

	var r0 *api.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*api.Secret, error)); ok {
		return returnFunc(ctx, mount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *api.Secret); ok {
		r0 = returnFunc(ctx, mount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, mount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksecretStore_listCertificates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'listCertificates'
type mocksecretStore_listCertificates_Call struct {
	*mock.Call
}

// listCertificates is a helper method to define mock.On call
//   - ctx context.Context
//   - mount string
func (_e *mocksecretStore_Expecter) listCertificates(ctx interface{}, mount interface{}) *mocksecretStore_listCertificates_Call {
	return &mocksecretStore_listCertificates_Call{Call: _e.mock.On("listCertificates", ctx, mount)}
}

func (_c *mocksecretStore_listCertificates_Call) Run(run func(ctx context.Context, mount string)) *mocksecretStore_listCertificates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocksecretStore_listCertificates_Call) Return(secret *api.Secret, err error) *mocksecretStore_listCertificates_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *mocksecretStore_listCertificates_Call) RunAndReturn(run func(ctx context.Context, mount string) (*api.Secret, error)) *mocksecretStore_listCertificates_Call {
	_c.Call.Return(run)
	return _c
}

// listIssuers provides a mock function for the type mocksecretStore
func (_mock *mocksecretStore) listIssuers(ctx context.Context, mount string) (*api.Secret, error) {
	ret := _mock.Called(ctx, mount)

	if len(ret) == 0 {
		panic("no return value specified for listIssuers")
	}

	var r0 *api.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*api.Secret, error)); ok {
		return returnFunc(ctx, mount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *api.Secret); ok {
		r0 = returnFunc(ctx, mount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, mount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksecretStore_listIssuers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'listIssuers'
type mocksecretStore_listIssuers_Call struct {
	*mock.Call
}

// listIssuers is a helper method to define mock.On call
//   - ctx context.Context
//   - mount string
func (_e *mocksecretStore_Expecter) listIssuers(ctx interface{}, mount interface{}) *mocksecretStore_listIssuers_Call {
	return &mocksecretStore_listIssuers_Call{Call: _e.mock.On("listIssuers", ctx, mount)}
}

func (_c *mocksecretStore_listIssuers_Call) Run(run func(ctx context.Context, mount string)) *mocksecretStore_listIssuers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocksecretStore_listIssuers_Call) Return(secret *api.Secret, err error) *mocksecretStore_listIssuers_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *mocksecretStore_listIssuers_Call) RunAndReturn(run func(ctx context.Context, mount string) (*api.Secret, error)) *mocksecretStore_listIssuers_Call {
	_c.Call.Return(run)
	return _c
}

// listMountPathsTypePki provides a mock function for the type mocksecretStore
func (_mock *mocksecretStore) listMountPathsTypePki(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for listMountPathsTypePki")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksecretStore_listMountPathsTypePki_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'listMountPathsTypePki'
type mocksecretStore_listMountPathsTypePki_Call struct {
	*mock.Call
}

// listMountPathsTypePki is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mocksecretStore_Expecter) listMountPathsTypePki(ctx interface{}) *mocksecretStore_listMountPathsTypePki_Call {
	return &mocksecretStore_listMountPathsTypePki_Call{Call: _e.mock.On("listMountPathsTypePki", ctx)}
}

func (_c *mocksecretStore_listMountPathsTypePki_Call) Run(run func(ctx context.Context)) *mocksecretStore_listMountPathsTypePki_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocksecretStore_listMountPathsTypePki_Call) Return(strings []string, err error) *mocksecretStore_listMountPathsTypePki_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *mocksecretStore_listMountPathsTypePki_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *mocksecretStore_listMountPathsTypePki_Call {
	_c.Call.Return(run)
	return _c
}

// readCertificate provides a mock function for the type mocksecretStore
func (_mock *mocksecretStore) readCertificate(ctx context.Context, mount string, serial string) (*api.Secret, error) {
	ret := _mock.Called(ctx, mount, serial)

	if len(ret) == 0 {
		panic("no return value specified for readCertificate")
	}

	var r0 *api.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*api.Secret, error)); ok {
		return returnFunc(ctx, mount, serial)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *api.Secret); ok {
		r0 = returnFunc(ctx, mount, serial)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, mount, serial)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksecretStore_readCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'readCertificate'
type mocksecretStore_readCertificate_Call struct {
	*mock.Call
}

// readCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - mount string
//   - serial string
func (_e *mocksecretStore_Expecter) readCertificate(ctx interface{}, mount interface{}, serial interface{}) *mocksecretStore_readCertificate_Call {
	return &mocksecretStore_readCertificate_Call{Call: _e.mock.On("readCertificate", ctx, mount, serial)}
}

func (_c *mocksecretStore_readCertificate_Call) Run(run func(ctx context.Context, mount string, serial string)) *mocksecretStore_readCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mocksecretStore_readCertificate_Call) Return(secret *api.Secret, err error) *mocksecretStore_readCertificate_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *mocksecretStore_readCertificate_Call) RunAndReturn(run func(ctx context.Context, mount string, serial string) (*api.Secret, error)) *mocksecretStore_readCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// readClusterConfiguration provides a mock function for the type mocksecretStore
func (_mock *mocksecretStore) readClusterConfiguration(ctx context.Context, mount string) (*api.Secret, error) {
	ret := _mock.Called(ctx, mount)

	if len(ret) == 0 {
		panic("no return value specified for readClusterConfiguration")
	}

	var r0 *api.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*api.Secret, error)); ok {
		return returnFunc(ctx, mount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *api.Secret); ok {
		r0 = returnFunc(ctx, mount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, mount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksecretStore_readClusterConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'readClusterConfiguration'
type mocksecretStore_readClusterConfiguration_Call struct {
	*mock.Call
}

// readClusterConfiguration is a helper method to define mock.On call
//   - ctx context.Context
//   - mount string
func (_e *mocksecretStore_Expecter) readClusterConfiguration(ctx interface{}, mount interface{}) *mocksecretStore_readClusterConfiguration_Call {
	return &mocksecretStore_readClusterConfiguration_Call{Call: _e.mock.On("readClusterConfiguration", ctx, mount)}
}

func (_c *mocksecretStore_readClusterConfiguration_Call) Run(run func(ctx context.Context, mount string)) *mocksecretStore_readClusterConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocksecretStore_readClusterConfiguration_Call) Return(secret *api.Secret, err error) *mocksecretStore_readClusterConfiguration_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *mocksecretStore_readClusterConfiguration_Call) RunAndReturn(run func(ctx context.Context, mount string) (*api.Secret, error)) *mocksecretStore_readClusterConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// readIssuer provides a mock function for the type mocksecretStore
func (_mock *mocksecretStore) readIssuer(ctx context.Context, mount string, id string) (*api.Secret, error) {
	ret := _mock.Called(ctx, mount, id)

	if len(ret) == 0 {
		panic("no return value specified for readIssuer")
	}

	var r0 *api.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*api.Secret, error)); ok {
		return returnFunc(ctx, mount, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *api.Secret); ok {
		r0 = returnFunc(ctx, mount, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, mount, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksecretStore_readIssuer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'readIssuer'
type mocksecretStore_readIssuer_Call struct {
	*mock.Call
}

// readIssuer is a helper method to define mock.On call
//   - ctx context.Context
//   - mount string
//   - id string
func (_e *mocksecretStore_Expecter) readIssuer(ctx interface{}, mount interface{}, id interface{}) *mocksecretStore_readIssuer_Call {
	return &mocksecretStore_readIssuer_Call{Call: _e.mock.On("readIssuer", ctx, mount, id)}
}

func (_c *mocksecretStore_readIssuer_Call) Run(run func(ctx context.Context, mount string, id string)) *mocksecretStore_readIssuer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mocksecretStore_readIssuer_Call) Return(secret *api.Secret, err error) *mocksecretStore_readIssuer_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *mocksecretStore_readIssuer_Call) RunAndReturn(run func(ctx context.Context, mount string, id string) (*api.Secret, error)) *mocksecretStore_readIssuer_Call {
	_c.Call.Return(run)
	return _c
}

// startTokenRenewal provides a mock function for the type mocksecretStore
func (_mock *mocksecretStore) startTokenRenewal(ctx context.Context, wg *sync.WaitGroup) {
	_mock.Called(ctx, wg)
	return
}

// mocksecretStore_startTokenRenewal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'startTokenRenewal'
type mocksecretStore_startTokenRenewal_Call struct {
	*mock.Call
}

// startTokenRenewal is a helper method to define mock.On call
//   - ctx context.Context
//   - wg *sync.WaitGroup
func (_e *mocksecretStore_Expecter) startTokenRenewal(ctx interface{}, wg interface{}) *mocksecretStore_startTokenRenewal_Call {
	return &mocksecretStore_startTokenRenewal_Call{Call: _e.mock.On("startTokenRenewal", ctx, wg)}
}

func (_c *mocksecretStore_startTokenRenewal_Call) Run(run func(ctx context.Context, wg *sync.WaitGroup)) *mocksecretStore_startTokenRenewal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sync.WaitGroup
		if args[1] != nil {
			arg1 = args[1].(*sync.WaitGroup)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocksecretStore_startTokenRenewal_Call) Return() *mocksecretStore_startTokenRenewal_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocksecretStore_startTokenRenewal_Call) RunAndReturn(run func(ctx context.Context, wg *sync.WaitGroup)) *mocksecretStore_startTokenRenewal_Call {
	_c.Run(run)
	return _c
}

// newMockldapConn creates a new instance of mockldapConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockldapConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockldapConn {
	mock := &mockldapConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockldapConn is an autogenerated mock type for the ldapConn type
type mockldapConn struct {
	mock.Mock
}

type mockldapConn_Expecter struct {
	mock *mock.Mock
}

func (_m *mockldapConn) EXPECT() *mockldapConn_Expecter {
	return &mockldapConn_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type mockldapConn
func (_mock *mockldapConn) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockldapConn_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type mockldapConn_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *mockldapConn_Expecter) Close() *mockldapConn_Close_Call {
	return &mockldapConn_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *mockldapConn_Close_Call) Run(run func()) *mockldapConn_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockldapConn_Close_Call) Return(err error) *mockldapConn_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockldapConn_Close_Call) RunAndReturn(run func() error) *mockldapConn_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type mockldapConn
func (_mock *mockldapConn) Search(searchRequest *ldap.SearchRequest) (*ldap.SearchResult, error) {
	ret := _mock.Called(searchRequest)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *ldap.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*ldap.SearchRequest) (*ldap.SearchResult, error)); ok {
		return returnFunc(searchRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(*ldap.SearchRequest) *ldap.SearchResult); ok {
		r0 = returnFunc(searchRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ldap.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*ldap.SearchRequest) error); ok {
		r1 = returnFunc(searchRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockldapConn_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type mockldapConn_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - searchRequest *ldap.SearchRequest
func (_e *mockldapConn_Expecter) Search(searchRequest interface{}) *mockldapConn_Search_Call {
	return &mockldapConn_Search_Call{Call: _e.mock.On("Search", searchRequest)}
}

func (_c *mockldapConn_Search_Call) Run(run func(searchRequest *ldap.SearchRequest)) *mockldapConn_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ldap.SearchRequest
		if args[0] != nil {
			arg0 = args[0].(*ldap.SearchRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockldapConn_Search_Call) Return(searchResult *ldap.SearchResult, err error) *mockldapConn_Search_Call {
	_c.Call.Return(searchResult, err)
	return _c
}

func (_c *mockldapConn_Search_Call) RunAndReturn(run func(searchRequest *ldap.SearchRequest) (*ldap.SearchResult, error)) *mockldapConn_Search_Call {
	_c.Call.Return(run)
	return _c
}

// newMockldapDialer creates a new instance of mockldapDialer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockldapDialer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockldapDialer {
	mock := &mockldapDialer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockldapDialer is an autogenerated mock type for the ldapDialer type
type mockldapDialer struct {
	mock.Mock
}

type mockldapDialer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockldapDialer) EXPECT() *mockldapDialer_Expecter {
	return &mockldapDialer_Expecter{mock: &_m.Mock}
}

// Dial provides a mock function for the type mockldapDialer
func (_mock *mockldapDialer) Dial(addr string, timeout time.Duration) (ldapConn, error) {
	ret := _mock.Called(addr, timeout)

	if len(ret) == 0 {
		panic("no return value specified for Dial")
	}

	var r0 ldapConn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, time.Duration) (ldapConn, error)); ok {
		return returnFunc(addr, timeout)
	}
	if returnFunc, ok := ret.Get(0).(func(string, time.Duration) ldapConn); ok {
		r0 = returnFunc(addr, timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ldapConn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, time.Duration) error); ok {
		r1 = returnFunc(addr, timeout)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockldapDialer_Dial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dial'
type mockldapDialer_Dial_Call struct {
	*mock.Call
}

// Dial is a helper method to define mock.On call
//   - addr string
//   - timeout time.Duration
func (_e *mockldapDialer_Expecter) Dial(addr interface{}, timeout interface{}) *mockldapDialer_Dial_Call {
	return &mockldapDialer_Dial_Call{Call: _e.mock.On("Dial", addr, timeout)}
}

func (_c *mockldapDialer_Dial_Call) Run(run func(addr string, timeout time.Duration)) *mockldapDialer_Dial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockldapDialer_Dial_Call) Return(ldapConnMoqParam ldapConn, err error) *mockldapDialer_Dial_Call {
	_c.Call.Return(ldapConnMoqParam, err)
	return _c
}

func (_c *mockldapDialer_Dial_Call) RunAndReturn(run func(addr string, timeout time.Duration) (ldapConn, error)) *mockldapDialer_Dial_Call {
	_c.Call.Return(run)
	return _c
}
