// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/featuregate"
)

var ReceiverPkiengineEmitCertMetricsFromIssuersFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"receiver.pkiengine.emitCertMetricsFromIssuers",
	featuregate.StageStable,
	featuregate.WithRegisterDescription("Switches issuer certificate emission from `pkiengine.issuer.x509.*` to `pkiengine.cert.x509.*`."),
	featuregate.WithRegisterReferenceURL("https://github.com/cvdtang/pkienginereceiver/issues/0"),
	featuregate.WithRegisterFromVersion("v0.151.0"),
	featuregate.WithRegisterToVersion("v0.154.0"),
)
