// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for pkiengine metrics.
type MetricsConfig struct {
	PkiengineCrlCacheEvictions          MetricConfig `mapstructure:"pkiengine.crl.cache.evictions"`
	PkiengineCrlCacheHits               MetricConfig `mapstructure:"pkiengine.crl.cache.hits"`
	PkiengineCrlCacheMisses             MetricConfig `mapstructure:"pkiengine.crl.cache.misses"`
	PkiengineCrlProcessingStatus        MetricConfig `mapstructure:"pkiengine.crl.processing_status"`
	PkiengineCrlX509NextUpdate          MetricConfig `mapstructure:"pkiengine.crl.x509.next_update"`
	PkiengineCrlX509RevokedCertificates MetricConfig `mapstructure:"pkiengine.crl.x509.revoked_certificates"`
	PkiengineCrlX509ThisUpdate          MetricConfig `mapstructure:"pkiengine.crl.x509.this_update"`
	PkiengineIssuerErrors               MetricConfig `mapstructure:"pkiengine.issuer.errors"`
	PkiengineIssuerX509NotAfter         MetricConfig `mapstructure:"pkiengine.issuer.x509.not_after"`
	PkiengineIssuerX509NotBefore        MetricConfig `mapstructure:"pkiengine.issuer.x509.not_before"`
	PkiengineMountCertificatesStored    MetricConfig `mapstructure:"pkiengine.mount.certificates_stored"`
	PkiengineMountErrors                MetricConfig `mapstructure:"pkiengine.mount.errors"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		PkiengineCrlCacheEvictions: MetricConfig{
			Enabled: true,
		},
		PkiengineCrlCacheHits: MetricConfig{
			Enabled: true,
		},
		PkiengineCrlCacheMisses: MetricConfig{
			Enabled: true,
		},
		PkiengineCrlProcessingStatus: MetricConfig{
			Enabled: true,
		},
		PkiengineCrlX509NextUpdate: MetricConfig{
			Enabled: true,
		},
		PkiengineCrlX509RevokedCertificates: MetricConfig{
			Enabled: true,
		},
		PkiengineCrlX509ThisUpdate: MetricConfig{
			Enabled: true,
		},
		PkiengineIssuerErrors: MetricConfig{
			Enabled: true,
		},
		PkiengineIssuerX509NotAfter: MetricConfig{
			Enabled: true,
		},
		PkiengineIssuerX509NotBefore: MetricConfig{
			Enabled: true,
		},
		PkiengineMountCertificatesStored: MetricConfig{
			Enabled: true,
		},
		PkiengineMountErrors: MetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for pkiengine resource attributes.
type ResourceAttributesConfig struct {
	EngineAddress   ResourceAttributeConfig `mapstructure:"engine.address"`
	EngineNamespace ResourceAttributeConfig `mapstructure:"engine.namespace"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		EngineAddress: ResourceAttributeConfig{
			Enabled: true,
		},
		EngineNamespace: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for pkiengine metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
