// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"

	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: DefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					PkiengineCrlCacheEvictions: MetricConfig{
						Enabled: true,
					},
					PkiengineCrlCacheHits: MetricConfig{
						Enabled: true,
					},
					PkiengineCrlCacheMisses: MetricConfig{
						Enabled: true,
					},
					PkiengineCrlProcessingStatus: MetricConfig{
						Enabled: true,
					},
					PkiengineCrlX509NextUpdate: MetricConfig{
						Enabled: true,
					},
					PkiengineCrlX509RevokedCertificates: MetricConfig{
						Enabled: true,
					},
					PkiengineCrlX509ThisUpdate: MetricConfig{
						Enabled: true,
					},
					PkiengineIssuerErrors: MetricConfig{
						Enabled: true,
					},
					PkiengineIssuerX509NotAfter: MetricConfig{
						Enabled: true,
					},
					PkiengineIssuerX509NotBefore: MetricConfig{
						Enabled: true,
					},
					PkiengineMountCertificatesStored: MetricConfig{
						Enabled: true,
					},
					PkiengineMountErrors: MetricConfig{
						Enabled: true,
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					EngineAddress:   ResourceAttributeConfig{Enabled: true},
					EngineNamespace: ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					PkiengineCrlCacheEvictions: MetricConfig{
						Enabled: false,
					},
					PkiengineCrlCacheHits: MetricConfig{
						Enabled: false,
					},
					PkiengineCrlCacheMisses: MetricConfig{
						Enabled: false,
					},
					PkiengineCrlProcessingStatus: MetricConfig{
						Enabled: false,
					},
					PkiengineCrlX509NextUpdate: MetricConfig{
						Enabled: false,
					},
					PkiengineCrlX509RevokedCertificates: MetricConfig{
						Enabled: false,
					},
					PkiengineCrlX509ThisUpdate: MetricConfig{
						Enabled: false,
					},
					PkiengineIssuerErrors: MetricConfig{
						Enabled: false,
					},
					PkiengineIssuerX509NotAfter: MetricConfig{
						Enabled: false,
					},
					PkiengineIssuerX509NotBefore: MetricConfig{
						Enabled: false,
					},
					PkiengineMountCertificatesStored: MetricConfig{
						Enabled: false,
					},
					PkiengineMountErrors: MetricConfig{
						Enabled: false,
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					EngineAddress:   ResourceAttributeConfig{Enabled: false},
					EngineNamespace: ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(MetricConfig{}, ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := DefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				EngineAddress:   ResourceAttributeConfig{Enabled: true},
				EngineNamespace: ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				EngineAddress:   ResourceAttributeConfig{Enabled: false},
				EngineNamespace: ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
