// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					PkiengineCertX509NotAfter: PkiengineCertX509NotAfterMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PkiengineCertX509NotAfterMetricAttributeKey{PkiengineCertX509NotAfterMetricAttributeKeyCertType, PkiengineCertX509NotAfterMetricAttributeKeyCertX509IssuerCommonName, PkiengineCertX509NotAfterMetricAttributeKeyCertX509SerialNumber, PkiengineCertX509NotAfterMetricAttributeKeyCertX509SubjectCommonName, PkiengineCertX509NotAfterMetricAttributeKeyCertX509SubjectCountry, PkiengineCertX509NotAfterMetricAttributeKeyCertX509SubjectOrganization, PkiengineCertX509NotAfterMetricAttributeKeyCertX509SubjectOrganizationalUnit, PkiengineCertX509NotAfterMetricAttributeKeyEngineMount, PkiengineCertX509NotAfterMetricAttributeKeyIssuerID},
					},
					PkiengineCertX509NotBefore: PkiengineCertX509NotBeforeMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PkiengineCertX509NotBeforeMetricAttributeKey{PkiengineCertX509NotBeforeMetricAttributeKeyCertType, PkiengineCertX509NotBeforeMetricAttributeKeyCertX509IssuerCommonName, PkiengineCertX509NotBeforeMetricAttributeKeyCertX509SerialNumber, PkiengineCertX509NotBeforeMetricAttributeKeyCertX509SubjectCommonName, PkiengineCertX509NotBeforeMetricAttributeKeyCertX509SubjectCountry, PkiengineCertX509NotBeforeMetricAttributeKeyCertX509SubjectOrganization, PkiengineCertX509NotBeforeMetricAttributeKeyCertX509SubjectOrganizationalUnit, PkiengineCertX509NotBeforeMetricAttributeKeyEngineMount, PkiengineCertX509NotBeforeMetricAttributeKeyIssuerID},
					},
					PkiengineCrlCacheEvictions: PkiengineCrlCacheEvictionsMetricConfig{
						Enabled: true,
					},
					PkiengineCrlCacheHits: PkiengineCrlCacheHitsMetricConfig{
						Enabled: true,
					},
					PkiengineCrlCacheMisses: PkiengineCrlCacheMissesMetricConfig{
						Enabled: true,
					},
					PkiengineCrlProcessingStatus: PkiengineCrlProcessingStatusMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PkiengineCrlProcessingStatusMetricAttributeKey{PkiengineCrlProcessingStatusMetricAttributeKeyCrlRole, PkiengineCrlProcessingStatusMetricAttributeKeyCrlKind, PkiengineCrlProcessingStatusMetricAttributeKeyCrlURI},
					},
					PkiengineCrlX509NextUpdate: PkiengineCrlX509NextUpdateMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PkiengineCrlX509NextUpdateMetricAttributeKey{PkiengineCrlX509NextUpdateMetricAttributeKeyCrlURI, PkiengineCrlX509NextUpdateMetricAttributeKeyCrlRole, PkiengineCrlX509NextUpdateMetricAttributeKeyCrlKind, PkiengineCrlX509NextUpdateMetricAttributeKeyCrlX509IssuerCommonName},
					},
					PkiengineCrlX509RevokedCertificates: PkiengineCrlX509RevokedCertificatesMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PkiengineCrlX509RevokedCertificatesMetricAttributeKey{PkiengineCrlX509RevokedCertificatesMetricAttributeKeyCrlURI, PkiengineCrlX509RevokedCertificatesMetricAttributeKeyCrlRole, PkiengineCrlX509RevokedCertificatesMetricAttributeKeyCrlKind, PkiengineCrlX509RevokedCertificatesMetricAttributeKeyCrlX509IssuerCommonName},
					},
					PkiengineCrlX509ThisUpdate: PkiengineCrlX509ThisUpdateMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PkiengineCrlX509ThisUpdateMetricAttributeKey{PkiengineCrlX509ThisUpdateMetricAttributeKeyCrlURI, PkiengineCrlX509ThisUpdateMetricAttributeKeyCrlRole, PkiengineCrlX509ThisUpdateMetricAttributeKeyCrlKind, PkiengineCrlX509ThisUpdateMetricAttributeKeyCrlX509IssuerCommonName},
					},
					PkiengineIssuerErrors: PkiengineIssuerErrorsMetricConfig{
						Enabled: true,
					},
					PkiengineMountCertificatesStored: PkiengineMountCertificatesStoredMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PkiengineMountCertificatesStoredMetricAttributeKey{PkiengineMountCertificatesStoredMetricAttributeKeyEngineMount},
					},
					PkiengineMountErrors: PkiengineMountErrorsMetricConfig{
						Enabled: true,
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					EngineAddress:   ResourceAttributeConfig{Enabled: true},
					EngineNamespace: ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					PkiengineCertX509NotAfter: PkiengineCertX509NotAfterMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PkiengineCertX509NotAfterMetricAttributeKey{PkiengineCertX509NotAfterMetricAttributeKeyCertType, PkiengineCertX509NotAfterMetricAttributeKeyCertX509IssuerCommonName, PkiengineCertX509NotAfterMetricAttributeKeyCertX509SerialNumber, PkiengineCertX509NotAfterMetricAttributeKeyCertX509SubjectCommonName, PkiengineCertX509NotAfterMetricAttributeKeyCertX509SubjectCountry, PkiengineCertX509NotAfterMetricAttributeKeyCertX509SubjectOrganization, PkiengineCertX509NotAfterMetricAttributeKeyCertX509SubjectOrganizationalUnit, PkiengineCertX509NotAfterMetricAttributeKeyEngineMount, PkiengineCertX509NotAfterMetricAttributeKeyIssuerID},
					},
					PkiengineCertX509NotBefore: PkiengineCertX509NotBeforeMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PkiengineCertX509NotBeforeMetricAttributeKey{PkiengineCertX509NotBeforeMetricAttributeKeyCertType, PkiengineCertX509NotBeforeMetricAttributeKeyCertX509IssuerCommonName, PkiengineCertX509NotBeforeMetricAttributeKeyCertX509SerialNumber, PkiengineCertX509NotBeforeMetricAttributeKeyCertX509SubjectCommonName, PkiengineCertX509NotBeforeMetricAttributeKeyCertX509SubjectCountry, PkiengineCertX509NotBeforeMetricAttributeKeyCertX509SubjectOrganization, PkiengineCertX509NotBeforeMetricAttributeKeyCertX509SubjectOrganizationalUnit, PkiengineCertX509NotBeforeMetricAttributeKeyEngineMount, PkiengineCertX509NotBeforeMetricAttributeKeyIssuerID},
					},
					PkiengineCrlCacheEvictions: PkiengineCrlCacheEvictionsMetricConfig{
						Enabled: false,
					},
					PkiengineCrlCacheHits: PkiengineCrlCacheHitsMetricConfig{
						Enabled: false,
					},
					PkiengineCrlCacheMisses: PkiengineCrlCacheMissesMetricConfig{
						Enabled: false,
					},
					PkiengineCrlProcessingStatus: PkiengineCrlProcessingStatusMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PkiengineCrlProcessingStatusMetricAttributeKey{PkiengineCrlProcessingStatusMetricAttributeKeyCrlRole, PkiengineCrlProcessingStatusMetricAttributeKeyCrlKind, PkiengineCrlProcessingStatusMetricAttributeKeyCrlURI},
					},
					PkiengineCrlX509NextUpdate: PkiengineCrlX509NextUpdateMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PkiengineCrlX509NextUpdateMetricAttributeKey{PkiengineCrlX509NextUpdateMetricAttributeKeyCrlURI, PkiengineCrlX509NextUpdateMetricAttributeKeyCrlRole, PkiengineCrlX509NextUpdateMetricAttributeKeyCrlKind, PkiengineCrlX509NextUpdateMetricAttributeKeyCrlX509IssuerCommonName},
					},
					PkiengineCrlX509RevokedCertificates: PkiengineCrlX509RevokedCertificatesMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PkiengineCrlX509RevokedCertificatesMetricAttributeKey{PkiengineCrlX509RevokedCertificatesMetricAttributeKeyCrlURI, PkiengineCrlX509RevokedCertificatesMetricAttributeKeyCrlRole, PkiengineCrlX509RevokedCertificatesMetricAttributeKeyCrlKind, PkiengineCrlX509RevokedCertificatesMetricAttributeKeyCrlX509IssuerCommonName},
					},
					PkiengineCrlX509ThisUpdate: PkiengineCrlX509ThisUpdateMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PkiengineCrlX509ThisUpdateMetricAttributeKey{PkiengineCrlX509ThisUpdateMetricAttributeKeyCrlURI, PkiengineCrlX509ThisUpdateMetricAttributeKeyCrlRole, PkiengineCrlX509ThisUpdateMetricAttributeKeyCrlKind, PkiengineCrlX509ThisUpdateMetricAttributeKeyCrlX509IssuerCommonName},
					},
					PkiengineIssuerErrors: PkiengineIssuerErrorsMetricConfig{
						Enabled: false,
					},
					PkiengineMountCertificatesStored: PkiengineMountCertificatesStoredMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PkiengineMountCertificatesStoredMetricAttributeKey{PkiengineMountCertificatesStoredMetricAttributeKeyEngineMount},
					},
					PkiengineMountErrors: PkiengineMountErrorsMetricConfig{
						Enabled: false,
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					EngineAddress:   ResourceAttributeConfig{Enabled: false},
					EngineNamespace: ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(PkiengineCertX509NotAfterMetricConfig{}, PkiengineCertX509NotBeforeMetricConfig{}, PkiengineCrlCacheEvictionsMetricConfig{}, PkiengineCrlCacheHitsMetricConfig{}, PkiengineCrlCacheMissesMetricConfig{}, PkiengineCrlProcessingStatusMetricConfig{}, PkiengineCrlX509NextUpdateMetricConfig{}, PkiengineCrlX509RevokedCertificatesMetricConfig{}, PkiengineCrlX509ThisUpdateMetricConfig{}, PkiengineIssuerErrorsMetricConfig{}, PkiengineMountCertificatesStoredMetricConfig{}, PkiengineMountErrorsMetricConfig{}, ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}
func TestPkiengineCertX509NotAfterMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PkiengineCertX509NotAfter
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PkiengineCertX509NotAfterMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric pkiengine.cert.x509.not_after doesn't have an attribute invalid, valid attributes: [cert.type, cert.x509.issuer.common_name, cert.x509.serial_number, cert.x509.subject.common_name, cert.x509.subject.country, cert.x509.subject.organization, cert.x509.subject.organizational_unit, engine.mount, issuer.id]")

	cfg = DefaultMetricsConfig().PkiengineCertX509NotAfter
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPkiengineCertX509NotBeforeMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PkiengineCertX509NotBefore
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PkiengineCertX509NotBeforeMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric pkiengine.cert.x509.not_before doesn't have an attribute invalid, valid attributes: [cert.type, cert.x509.issuer.common_name, cert.x509.serial_number, cert.x509.subject.common_name, cert.x509.subject.country, cert.x509.subject.organization, cert.x509.subject.organizational_unit, engine.mount, issuer.id]")

	cfg = DefaultMetricsConfig().PkiengineCertX509NotBefore
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPkiengineCrlProcessingStatusMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PkiengineCrlProcessingStatus
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PkiengineCrlProcessingStatusMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric pkiengine.crl.processing_status doesn't have an attribute invalid, valid attributes: [crl.role, crl.kind, crl.uri]")

	cfg = DefaultMetricsConfig().PkiengineCrlProcessingStatus
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPkiengineCrlX509NextUpdateMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PkiengineCrlX509NextUpdate
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PkiengineCrlX509NextUpdateMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric pkiengine.crl.x509.next_update doesn't have an attribute invalid, valid attributes: [crl.uri, crl.role, crl.kind, crl.x509.issuer.common_name]")

	cfg = DefaultMetricsConfig().PkiengineCrlX509NextUpdate
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPkiengineCrlX509RevokedCertificatesMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PkiengineCrlX509RevokedCertificates
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PkiengineCrlX509RevokedCertificatesMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric pkiengine.crl.x509.revoked_certificates doesn't have an attribute invalid, valid attributes: [crl.uri, crl.role, crl.kind, crl.x509.issuer.common_name]")

	cfg = DefaultMetricsConfig().PkiengineCrlX509RevokedCertificates
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPkiengineCrlX509ThisUpdateMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PkiengineCrlX509ThisUpdate
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PkiengineCrlX509ThisUpdateMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric pkiengine.crl.x509.this_update doesn't have an attribute invalid, valid attributes: [crl.uri, crl.role, crl.kind, crl.x509.issuer.common_name]")

	cfg = DefaultMetricsConfig().PkiengineCrlX509ThisUpdate
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPkiengineMountCertificatesStoredMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PkiengineMountCertificatesStored
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PkiengineMountCertificatesStoredMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric pkiengine.mount.certificates_stored doesn't have an attribute invalid, valid attributes: [engine.mount]")

	cfg = DefaultMetricsConfig().PkiengineMountCertificatesStored
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				EngineAddress:   ResourceAttributeConfig{Enabled: true},
				EngineNamespace: ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				EngineAddress:   ResourceAttributeConfig{Enabled: false},
				EngineNamespace: ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
