// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"time"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/filter"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
)

// AttributeCrlKind specifies the value crl.kind attribute.
type AttributeCrlKind int

const (
	_ AttributeCrlKind = iota
	AttributeCrlKindBase
	AttributeCrlKindDelta
)

// String returns the string representation of the AttributeCrlKind.
func (av AttributeCrlKind) String() string {
	switch av {
	case AttributeCrlKindBase:
		return "base"
	case AttributeCrlKindDelta:
		return "delta"
	}
	return ""
}

// MapAttributeCrlKind is a helper map of string to AttributeCrlKind attribute value.
var MapAttributeCrlKind = map[string]AttributeCrlKind{
	"base":  AttributeCrlKindBase,
	"delta": AttributeCrlKindDelta,
}

// AttributeCrlRole specifies the value crl.role attribute.
type AttributeCrlRole int

const (
	_ AttributeCrlRole = iota
	AttributeCrlRoleSubject
	AttributeCrlRoleIssuer
)

// String returns the string representation of the AttributeCrlRole.
func (av AttributeCrlRole) String() string {
	switch av {
	case AttributeCrlRoleSubject:
		return "subject"
	case AttributeCrlRoleIssuer:
		return "issuer"
	}
	return ""
}

// MapAttributeCrlRole is a helper map of string to AttributeCrlRole attribute value.
var MapAttributeCrlRole = map[string]AttributeCrlRole{
	"subject": AttributeCrlRoleSubject,
	"issuer":  AttributeCrlRoleIssuer,
}

var MetricsInfo = metricsInfo{
	PkiengineCrlCacheEvictions: metricInfo{
		Name: "pkiengine.crl.cache.evictions",
	},
	PkiengineCrlCacheHits: metricInfo{
		Name: "pkiengine.crl.cache.hits",
	},
	PkiengineCrlCacheMisses: metricInfo{
		Name: "pkiengine.crl.cache.misses",
	},
	PkiengineCrlProcessingStatus: metricInfo{
		Name: "pkiengine.crl.processing_status",
	},
	PkiengineCrlX509NextUpdate: metricInfo{
		Name: "pkiengine.crl.x509.next_update",
	},
	PkiengineCrlX509RevokedCertificates: metricInfo{
		Name: "pkiengine.crl.x509.revoked_certificates",
	},
	PkiengineCrlX509ThisUpdate: metricInfo{
		Name: "pkiengine.crl.x509.this_update",
	},
	PkiengineIssuerErrors: metricInfo{
		Name: "pkiengine.issuer.errors",
	},
	PkiengineIssuerX509NotAfter: metricInfo{
		Name: "pkiengine.issuer.x509.not_after",
	},
	PkiengineIssuerX509NotBefore: metricInfo{
		Name: "pkiengine.issuer.x509.not_before",
	},
	PkiengineMountCertificatesStored: metricInfo{
		Name: "pkiengine.mount.certificates_stored",
	},
	PkiengineMountErrors: metricInfo{
		Name: "pkiengine.mount.errors",
	},
}

type metricsInfo struct {
	PkiengineCrlCacheEvictions          metricInfo
	PkiengineCrlCacheHits               metricInfo
	PkiengineCrlCacheMisses             metricInfo
	PkiengineCrlProcessingStatus        metricInfo
	PkiengineCrlX509NextUpdate          metricInfo
	PkiengineCrlX509RevokedCertificates metricInfo
	PkiengineCrlX509ThisUpdate          metricInfo
	PkiengineIssuerErrors               metricInfo
	PkiengineIssuerX509NotAfter         metricInfo
	PkiengineIssuerX509NotBefore        metricInfo
	PkiengineMountCertificatesStored    metricInfo
	PkiengineMountErrors                metricInfo
}

type metricInfo struct {
	Name string
}

type metricPkiengineCrlCacheEvictions struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills pkiengine.crl.cache.evictions metric with initial data.
func (m *metricPkiengineCrlCacheEvictions) init() {
	m.data.SetName("pkiengine.crl.cache.evictions")
	m.data.SetDescription("Number of CRL cache evictions.")
	m.data.SetUnit("{evictions}")
	m.data.SetEmptyGauge()
}

func (m *metricPkiengineCrlCacheEvictions) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPkiengineCrlCacheEvictions) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPkiengineCrlCacheEvictions) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPkiengineCrlCacheEvictions(cfg MetricConfig) metricPkiengineCrlCacheEvictions {
	m := metricPkiengineCrlCacheEvictions{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricPkiengineCrlCacheHits struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills pkiengine.crl.cache.hits metric with initial data.
func (m *metricPkiengineCrlCacheHits) init() {
	m.data.SetName("pkiengine.crl.cache.hits")
	m.data.SetDescription("Number of CRL cache hits.")
	m.data.SetUnit("{hits}")
	m.data.SetEmptyGauge()
}

func (m *metricPkiengineCrlCacheHits) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPkiengineCrlCacheHits) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPkiengineCrlCacheHits) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPkiengineCrlCacheHits(cfg MetricConfig) metricPkiengineCrlCacheHits {
	m := metricPkiengineCrlCacheHits{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricPkiengineCrlCacheMisses struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills pkiengine.crl.cache.misses metric with initial data.
func (m *metricPkiengineCrlCacheMisses) init() {
	m.data.SetName("pkiengine.crl.cache.misses")
	m.data.SetDescription("Number of CRL cache misses.")
	m.data.SetUnit("{misses}")
	m.data.SetEmptyGauge()
}

func (m *metricPkiengineCrlCacheMisses) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPkiengineCrlCacheMisses) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPkiengineCrlCacheMisses) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPkiengineCrlCacheMisses(cfg MetricConfig) metricPkiengineCrlCacheMisses {
	m := metricPkiengineCrlCacheMisses{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricPkiengineCrlProcessingStatus struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills pkiengine.crl.processing_status metric with initial data.
func (m *metricPkiengineCrlProcessingStatus) init() {
	m.data.SetName("pkiengine.crl.processing_status")
	m.data.SetDescription("CRL processing status as an integer value.")
	m.data.SetUnit("{status}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPkiengineCrlProcessingStatus) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, crlRoleAttributeValue string, crlKindAttributeValue string, crlURIAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("crl.role", crlRoleAttributeValue)
	dp.Attributes().PutStr("crl.kind", crlKindAttributeValue)
	dp.Attributes().PutStr("crl.uri", crlURIAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPkiengineCrlProcessingStatus) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPkiengineCrlProcessingStatus) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPkiengineCrlProcessingStatus(cfg MetricConfig) metricPkiengineCrlProcessingStatus {
	m := metricPkiengineCrlProcessingStatus{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricPkiengineCrlX509NextUpdate struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills pkiengine.crl.x509.next_update metric with initial data.
func (m *metricPkiengineCrlX509NextUpdate) init() {
	m.data.SetName("pkiengine.crl.x509.next_update")
	m.data.SetDescription("Time until the CRL `nextUpdate` field.")
	m.data.SetUnit("minutes")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPkiengineCrlX509NextUpdate) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, crlURIAttributeValue string, crlRoleAttributeValue string, crlKindAttributeValue string, crlX509IssuerCommonNameAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("crl.uri", crlURIAttributeValue)
	dp.Attributes().PutStr("crl.role", crlRoleAttributeValue)
	dp.Attributes().PutStr("crl.kind", crlKindAttributeValue)
	dp.Attributes().PutStr("crl.x509.issuer.common_name", crlX509IssuerCommonNameAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPkiengineCrlX509NextUpdate) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPkiengineCrlX509NextUpdate) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPkiengineCrlX509NextUpdate(cfg MetricConfig) metricPkiengineCrlX509NextUpdate {
	m := metricPkiengineCrlX509NextUpdate{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricPkiengineCrlX509RevokedCertificates struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills pkiengine.crl.x509.revoked_certificates metric with initial data.
func (m *metricPkiengineCrlX509RevokedCertificates) init() {
	m.data.SetName("pkiengine.crl.x509.revoked_certificates")
	m.data.SetDescription("Number of certificates listed in the CRL `revokedCertificates` field.")
	m.data.SetUnit("count")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPkiengineCrlX509RevokedCertificates) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, crlURIAttributeValue string, crlRoleAttributeValue string, crlKindAttributeValue string, crlX509IssuerCommonNameAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("crl.uri", crlURIAttributeValue)
	dp.Attributes().PutStr("crl.role", crlRoleAttributeValue)
	dp.Attributes().PutStr("crl.kind", crlKindAttributeValue)
	dp.Attributes().PutStr("crl.x509.issuer.common_name", crlX509IssuerCommonNameAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPkiengineCrlX509RevokedCertificates) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPkiengineCrlX509RevokedCertificates) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPkiengineCrlX509RevokedCertificates(cfg MetricConfig) metricPkiengineCrlX509RevokedCertificates {
	m := metricPkiengineCrlX509RevokedCertificates{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricPkiengineCrlX509ThisUpdate struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills pkiengine.crl.x509.this_update metric with initial data.
func (m *metricPkiengineCrlX509ThisUpdate) init() {
	m.data.SetName("pkiengine.crl.x509.this_update")
	m.data.SetDescription("Time since the CRL `thisUpdate` field.")
	m.data.SetUnit("minutes")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPkiengineCrlX509ThisUpdate) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, crlURIAttributeValue string, crlRoleAttributeValue string, crlKindAttributeValue string, crlX509IssuerCommonNameAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("crl.uri", crlURIAttributeValue)
	dp.Attributes().PutStr("crl.role", crlRoleAttributeValue)
	dp.Attributes().PutStr("crl.kind", crlKindAttributeValue)
	dp.Attributes().PutStr("crl.x509.issuer.common_name", crlX509IssuerCommonNameAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPkiengineCrlX509ThisUpdate) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPkiengineCrlX509ThisUpdate) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPkiengineCrlX509ThisUpdate(cfg MetricConfig) metricPkiengineCrlX509ThisUpdate {
	m := metricPkiengineCrlX509ThisUpdate{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricPkiengineIssuerErrors struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills pkiengine.issuer.errors metric with initial data.
func (m *metricPkiengineIssuerErrors) init() {
	m.data.SetName("pkiengine.issuer.errors")
	m.data.SetDescription("Number of errors that occurred while processing issuers.")
	m.data.SetUnit("{errors}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityUnspecified)
}

func (m *metricPkiengineIssuerErrors) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPkiengineIssuerErrors) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPkiengineIssuerErrors) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPkiengineIssuerErrors(cfg MetricConfig) metricPkiengineIssuerErrors {
	m := metricPkiengineIssuerErrors{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricPkiengineIssuerX509NotAfter struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills pkiengine.issuer.x509.not_after metric with initial data.
func (m *metricPkiengineIssuerX509NotAfter) init() {
	m.data.SetName("pkiengine.issuer.x509.not_after")
	m.data.SetDescription("Time until certificate expiration as specified by the `notAfter` field.")
	m.data.SetUnit("minutes")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPkiengineIssuerX509NotAfter) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, issuerIDAttributeValue string, certX509SubjectCommonNameAttributeValue string, certX509IssuerCommonNameAttributeValue string, engineMountAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("issuer.id", issuerIDAttributeValue)
	dp.Attributes().PutStr("cert.x509.subject.common_name", certX509SubjectCommonNameAttributeValue)
	dp.Attributes().PutStr("cert.x509.issuer.common_name", certX509IssuerCommonNameAttributeValue)
	dp.Attributes().PutStr("engine.mount", engineMountAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPkiengineIssuerX509NotAfter) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPkiengineIssuerX509NotAfter) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPkiengineIssuerX509NotAfter(cfg MetricConfig) metricPkiengineIssuerX509NotAfter {
	m := metricPkiengineIssuerX509NotAfter{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricPkiengineIssuerX509NotBefore struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills pkiengine.issuer.x509.not_before metric with initial data.
func (m *metricPkiengineIssuerX509NotBefore) init() {
	m.data.SetName("pkiengine.issuer.x509.not_before")
	m.data.SetDescription("Time util certificate validity start as specified by the `notBefore` field.")
	m.data.SetUnit("minutes")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPkiengineIssuerX509NotBefore) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, issuerIDAttributeValue string, certX509SubjectCommonNameAttributeValue string, certX509IssuerCommonNameAttributeValue string, engineMountAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("issuer.id", issuerIDAttributeValue)
	dp.Attributes().PutStr("cert.x509.subject.common_name", certX509SubjectCommonNameAttributeValue)
	dp.Attributes().PutStr("cert.x509.issuer.common_name", certX509IssuerCommonNameAttributeValue)
	dp.Attributes().PutStr("engine.mount", engineMountAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPkiengineIssuerX509NotBefore) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPkiengineIssuerX509NotBefore) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPkiengineIssuerX509NotBefore(cfg MetricConfig) metricPkiengineIssuerX509NotBefore {
	m := metricPkiengineIssuerX509NotBefore{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricPkiengineMountCertificatesStored struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills pkiengine.mount.certificates_stored metric with initial data.
func (m *metricPkiengineMountCertificatesStored) init() {
	m.data.SetName("pkiengine.mount.certificates_stored")
	m.data.SetDescription("Number of certificates stored in the mount.")
	m.data.SetUnit("{certificates_stored}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricPkiengineMountCertificatesStored) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, engineMountAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("engine.mount", engineMountAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPkiengineMountCertificatesStored) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPkiengineMountCertificatesStored) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPkiengineMountCertificatesStored(cfg MetricConfig) metricPkiengineMountCertificatesStored {
	m := metricPkiengineMountCertificatesStored{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricPkiengineMountErrors struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills pkiengine.mount.errors metric with initial data.
func (m *metricPkiengineMountErrors) init() {
	m.data.SetName("pkiengine.mount.errors")
	m.data.SetDescription("Number of errors that occurred while processing mounts.")
	m.data.SetUnit("{errors}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(false)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityUnspecified)
}

func (m *metricPkiengineMountErrors) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricPkiengineMountErrors) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricPkiengineMountErrors) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricPkiengineMountErrors(cfg MetricConfig) metricPkiengineMountErrors {
	m := metricPkiengineMountErrors{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                                    MetricsBuilderConfig // config of the metrics builder.
	startTime                                 pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                           int                  // maximum observed number of metrics per resource.
	metricsBuffer                             pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                                 component.BuildInfo  // contains version information.
	resourceAttributeIncludeFilter            map[string]filter.Filter
	resourceAttributeExcludeFilter            map[string]filter.Filter
	metricPkiengineCrlCacheEvictions          metricPkiengineCrlCacheEvictions
	metricPkiengineCrlCacheHits               metricPkiengineCrlCacheHits
	metricPkiengineCrlCacheMisses             metricPkiengineCrlCacheMisses
	metricPkiengineCrlProcessingStatus        metricPkiengineCrlProcessingStatus
	metricPkiengineCrlX509NextUpdate          metricPkiengineCrlX509NextUpdate
	metricPkiengineCrlX509RevokedCertificates metricPkiengineCrlX509RevokedCertificates
	metricPkiengineCrlX509ThisUpdate          metricPkiengineCrlX509ThisUpdate
	metricPkiengineIssuerErrors               metricPkiengineIssuerErrors
	metricPkiengineIssuerX509NotAfter         metricPkiengineIssuerX509NotAfter
	metricPkiengineIssuerX509NotBefore        metricPkiengineIssuerX509NotBefore
	metricPkiengineMountCertificatesStored    metricPkiengineMountCertificatesStored
	metricPkiengineMountErrors                metricPkiengineMountErrors
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                                    mbc,
		startTime:                                 pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                             pmetric.NewMetrics(),
		buildInfo:                                 settings.BuildInfo,
		metricPkiengineCrlCacheEvictions:          newMetricPkiengineCrlCacheEvictions(mbc.Metrics.PkiengineCrlCacheEvictions),
		metricPkiengineCrlCacheHits:               newMetricPkiengineCrlCacheHits(mbc.Metrics.PkiengineCrlCacheHits),
		metricPkiengineCrlCacheMisses:             newMetricPkiengineCrlCacheMisses(mbc.Metrics.PkiengineCrlCacheMisses),
		metricPkiengineCrlProcessingStatus:        newMetricPkiengineCrlProcessingStatus(mbc.Metrics.PkiengineCrlProcessingStatus),
		metricPkiengineCrlX509NextUpdate:          newMetricPkiengineCrlX509NextUpdate(mbc.Metrics.PkiengineCrlX509NextUpdate),
		metricPkiengineCrlX509RevokedCertificates: newMetricPkiengineCrlX509RevokedCertificates(mbc.Metrics.PkiengineCrlX509RevokedCertificates),
		metricPkiengineCrlX509ThisUpdate:          newMetricPkiengineCrlX509ThisUpdate(mbc.Metrics.PkiengineCrlX509ThisUpdate),
		metricPkiengineIssuerErrors:               newMetricPkiengineIssuerErrors(mbc.Metrics.PkiengineIssuerErrors),
		metricPkiengineIssuerX509NotAfter:         newMetricPkiengineIssuerX509NotAfter(mbc.Metrics.PkiengineIssuerX509NotAfter),
		metricPkiengineIssuerX509NotBefore:        newMetricPkiengineIssuerX509NotBefore(mbc.Metrics.PkiengineIssuerX509NotBefore),
		metricPkiengineMountCertificatesStored:    newMetricPkiengineMountCertificatesStored(mbc.Metrics.PkiengineMountCertificatesStored),
		metricPkiengineMountErrors:                newMetricPkiengineMountErrors(mbc.Metrics.PkiengineMountErrors),
		resourceAttributeIncludeFilter:            make(map[string]filter.Filter),
		resourceAttributeExcludeFilter:            make(map[string]filter.Filter),
	}
	if mbc.ResourceAttributes.EngineAddress.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["engine.address"] = filter.CreateFilter(mbc.ResourceAttributes.EngineAddress.MetricsInclude)
	}
	if mbc.ResourceAttributes.EngineAddress.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["engine.address"] = filter.CreateFilter(mbc.ResourceAttributes.EngineAddress.MetricsExclude)
	}
	if mbc.ResourceAttributes.EngineNamespace.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["engine.namespace"] = filter.CreateFilter(mbc.ResourceAttributes.EngineNamespace.MetricsInclude)
	}
	if mbc.ResourceAttributes.EngineNamespace.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["engine.namespace"] = filter.CreateFilter(mbc.ResourceAttributes.EngineNamespace.MetricsExclude)
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// NewResourceBuilder returns a new resource builder that should be used to build a resource associated with for the emitted metrics.
func (mb *MetricsBuilder) NewResourceBuilder() *ResourceBuilder {
	return NewResourceBuilder(mb.config.ResourceAttributes)
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricPkiengineCrlCacheEvictions.emit(ils.Metrics())
	mb.metricPkiengineCrlCacheHits.emit(ils.Metrics())
	mb.metricPkiengineCrlCacheMisses.emit(ils.Metrics())
	mb.metricPkiengineCrlProcessingStatus.emit(ils.Metrics())
	mb.metricPkiengineCrlX509NextUpdate.emit(ils.Metrics())
	mb.metricPkiengineCrlX509RevokedCertificates.emit(ils.Metrics())
	mb.metricPkiengineCrlX509ThisUpdate.emit(ils.Metrics())
	mb.metricPkiengineIssuerErrors.emit(ils.Metrics())
	mb.metricPkiengineIssuerX509NotAfter.emit(ils.Metrics())
	mb.metricPkiengineIssuerX509NotBefore.emit(ils.Metrics())
	mb.metricPkiengineMountCertificatesStored.emit(ils.Metrics())
	mb.metricPkiengineMountErrors.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}
	for attr, filter := range mb.resourceAttributeIncludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && !filter.Matches(val.AsString()) {
			return
		}
	}
	for attr, filter := range mb.resourceAttributeExcludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && filter.Matches(val.AsString()) {
			return
		}
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordPkiengineCrlCacheEvictionsDataPoint adds a data point to pkiengine.crl.cache.evictions metric.
func (mb *MetricsBuilder) RecordPkiengineCrlCacheEvictionsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricPkiengineCrlCacheEvictions.recordDataPoint(mb.startTime, ts, val)
}

// RecordPkiengineCrlCacheHitsDataPoint adds a data point to pkiengine.crl.cache.hits metric.
func (mb *MetricsBuilder) RecordPkiengineCrlCacheHitsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricPkiengineCrlCacheHits.recordDataPoint(mb.startTime, ts, val)
}

// RecordPkiengineCrlCacheMissesDataPoint adds a data point to pkiengine.crl.cache.misses metric.
func (mb *MetricsBuilder) RecordPkiengineCrlCacheMissesDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricPkiengineCrlCacheMisses.recordDataPoint(mb.startTime, ts, val)
}

// RecordPkiengineCrlProcessingStatusDataPoint adds a data point to pkiengine.crl.processing_status metric.
func (mb *MetricsBuilder) RecordPkiengineCrlProcessingStatusDataPoint(ts pcommon.Timestamp, val int64, crlRoleAttributeValue AttributeCrlRole, crlKindAttributeValue AttributeCrlKind, crlURIAttributeValue string) {
	mb.metricPkiengineCrlProcessingStatus.recordDataPoint(mb.startTime, ts, val, crlRoleAttributeValue.String(), crlKindAttributeValue.String(), crlURIAttributeValue)
}

// RecordPkiengineCrlX509NextUpdateDataPoint adds a data point to pkiengine.crl.x509.next_update metric.
func (mb *MetricsBuilder) RecordPkiengineCrlX509NextUpdateDataPoint(ts pcommon.Timestamp, val int64, crlURIAttributeValue string, crlRoleAttributeValue AttributeCrlRole, crlKindAttributeValue AttributeCrlKind, crlX509IssuerCommonNameAttributeValue string) {
	mb.metricPkiengineCrlX509NextUpdate.recordDataPoint(mb.startTime, ts, val, crlURIAttributeValue, crlRoleAttributeValue.String(), crlKindAttributeValue.String(), crlX509IssuerCommonNameAttributeValue)
}

// RecordPkiengineCrlX509RevokedCertificatesDataPoint adds a data point to pkiengine.crl.x509.revoked_certificates metric.
func (mb *MetricsBuilder) RecordPkiengineCrlX509RevokedCertificatesDataPoint(ts pcommon.Timestamp, val int64, crlURIAttributeValue string, crlRoleAttributeValue AttributeCrlRole, crlKindAttributeValue AttributeCrlKind, crlX509IssuerCommonNameAttributeValue string) {
	mb.metricPkiengineCrlX509RevokedCertificates.recordDataPoint(mb.startTime, ts, val, crlURIAttributeValue, crlRoleAttributeValue.String(), crlKindAttributeValue.String(), crlX509IssuerCommonNameAttributeValue)
}

// RecordPkiengineCrlX509ThisUpdateDataPoint adds a data point to pkiengine.crl.x509.this_update metric.
func (mb *MetricsBuilder) RecordPkiengineCrlX509ThisUpdateDataPoint(ts pcommon.Timestamp, val int64, crlURIAttributeValue string, crlRoleAttributeValue AttributeCrlRole, crlKindAttributeValue AttributeCrlKind, crlX509IssuerCommonNameAttributeValue string) {
	mb.metricPkiengineCrlX509ThisUpdate.recordDataPoint(mb.startTime, ts, val, crlURIAttributeValue, crlRoleAttributeValue.String(), crlKindAttributeValue.String(), crlX509IssuerCommonNameAttributeValue)
}

// RecordPkiengineIssuerErrorsDataPoint adds a data point to pkiengine.issuer.errors metric.
func (mb *MetricsBuilder) RecordPkiengineIssuerErrorsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricPkiengineIssuerErrors.recordDataPoint(mb.startTime, ts, val)
}

// RecordPkiengineIssuerX509NotAfterDataPoint adds a data point to pkiengine.issuer.x509.not_after metric.
func (mb *MetricsBuilder) RecordPkiengineIssuerX509NotAfterDataPoint(ts pcommon.Timestamp, val int64, issuerIDAttributeValue string, certX509SubjectCommonNameAttributeValue string, certX509IssuerCommonNameAttributeValue string, engineMountAttributeValue string) {
	mb.metricPkiengineIssuerX509NotAfter.recordDataPoint(mb.startTime, ts, val, issuerIDAttributeValue, certX509SubjectCommonNameAttributeValue, certX509IssuerCommonNameAttributeValue, engineMountAttributeValue)
}

// RecordPkiengineIssuerX509NotBeforeDataPoint adds a data point to pkiengine.issuer.x509.not_before metric.
func (mb *MetricsBuilder) RecordPkiengineIssuerX509NotBeforeDataPoint(ts pcommon.Timestamp, val int64, issuerIDAttributeValue string, certX509SubjectCommonNameAttributeValue string, certX509IssuerCommonNameAttributeValue string, engineMountAttributeValue string) {
	mb.metricPkiengineIssuerX509NotBefore.recordDataPoint(mb.startTime, ts, val, issuerIDAttributeValue, certX509SubjectCommonNameAttributeValue, certX509IssuerCommonNameAttributeValue, engineMountAttributeValue)
}

// RecordPkiengineMountCertificatesStoredDataPoint adds a data point to pkiengine.mount.certificates_stored metric.
func (mb *MetricsBuilder) RecordPkiengineMountCertificatesStoredDataPoint(ts pcommon.Timestamp, val int64, engineMountAttributeValue string) {
	mb.metricPkiengineMountCertificatesStored.recordDataPoint(mb.startTime, ts, val, engineMountAttributeValue)
}

// RecordPkiengineMountErrorsDataPoint adds a data point to pkiengine.mount.errors metric.
func (mb *MetricsBuilder) RecordPkiengineMountErrorsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricPkiengineMountErrors.recordDataPoint(mb.startTime, ts, val)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
