name: CI

on:
  push:
  workflow_dispatch:

jobs:
  quality-gate:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check for changes
        uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: filter
        with:
          filters: |
            src: &src
              - '.github/workflows/ci.yml'
              - 'justfile'
              - 'go.{mod,sum}'
              - '**/*.go'
            integration:
              - *src
              - 'test/terraform/*.tf'
              - 'test/testdata/*.yaml'
            config:
              - *src
              - 'test/builder-config.yaml'

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_wrapper: false

      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0

      - name: Download modules & check consistency
        if: steps.filter.outputs.src == 'true'
        run: go mod download && just tidy-check

      - name: Run mdatagen & commit if changed
        if: steps.filter.outputs.src == 'true' && startsWith(github.ref, 'refs/heads/')
        run: |
          just mdatagen
          if ! git diff --quiet; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "chore: update generated metadata"
            git push origin HEAD:${GITHUB_REF_NAME}
          fi

      - name: Golangci-lint
        if: steps.filter.outputs.src == 'true'
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0

      - name: Unit tests
        if: steps.filter.outputs.src == 'true'
        run: just test-short

      - name: Integration tests
        if: steps.filter.outputs.integration == 'true'
        run: just test-long

      - name: Test OTEL collector build
        if: steps.filter.outputs.config == 'true'
        run: just build-oc
